base/urls.py
from django.urls import path
from base import views


urlpatterns = [
    path('', views.homepage, name='home'),
    path('about/', views.about, name= "about"),
    path('refund-policy/', views.refund, name= "refund"),
    path('terms-of-sales/', views.terms, name= "terms"),
    path('privacy-policy/', views.privacy, name= "privacy"),
    path('legal-notice/', views.legalNotice, name= "legalNotice"),
    path('shipping-policy/', views.shipping, name= "shipping"),
]

djangoparisianist/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('store/', include('store.urls')),
    path('user/', include('userauths.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views


urlpatterns = [
path('place_order/', views.place_order, name='place_order'),
path('paypal_payment/', views.paypal_payment, name='paypal_payment'),
path('stripe_payment/', views.stripe_payment, name='stripe_payment'),

# path('stripe_success/', views.stripe_success, name='stripe_success'),
# path('stripe_cancel/', views.stripe_cancel, name='stripe_cancel'),
path('webhook/', views.stripe_webhook, name="webhook"), # new
path('config/', views.stripe_config, name="config"),

#    path('paypal_payment/<payment_method>/', views.paypal_payment, name='paypal_payment'),
path('order_complete/', views.order_complete, name='order_complete'),
    # path('stripe-payment/', views.stripe_payment, name='stripe_payment'),
    # path('paypal-payment/', views.paypal_payment, name='paypal_payment'),
]

orders/models.py
from django.db import models
from userauths.models import Account
from store.models import Product, Variation
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Pending', 'Pending'),
        ('Processing', 'Processing'),
        ('Shipped', 'Shipped'),
        ('Refunding', 'Refunding'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    DELIVERY_METHOD = (
        ("DHL", "DHL"),
        ("Colissimo", "Colissimo"),
    )

    PAYMENT_METHOD = (
        ("Card", "Card"),
        ("Paypal", "Paypal"),
    )
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    # Existing fields...
    tracking_number = models.CharField(max_length=50, blank=True, null=True)
    # Add this line
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, null=True, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    postcode = models.CharField(max_length=50)
    order_total = models.FloatField()
    tax = models.FloatField()
    payment_intent = models.CharField(max_length=250, blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    delivery_method = models.CharField(
        max_length=10, choices=DELIVERY_METHOD)
    payment_method = models.CharField(
        max_length=10, choices=PAYMENT_METHOD, default='Card')
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    paid_amount = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name
    
    #Send message to user when the colis is delivered
    def save(self, *args, **kwargs):
        # Déterminer si c'est une mise à jour et obtenir l'ancien statut
        if self.pk:
            old_status = Order.objects.get(pk=self.pk).status
        else:
            old_status = None

        super().save(*args, **kwargs)

        # Envoyer un email si le statut passe à 'Shipped'
        if old_status != 'Shipped' and self.status == 'Shipped' and self.tracking_number:
            subject = 'Votre commande a été expédiée'
            message = render_to_string(
                'orders/emails/shipment_email.html', {'order': self})
            send_mail(subject, '', settings.DEFAULT_FROM_EMAIL,
                      [self.email], html_message=message)
            print(message)
        if old_status != 'Completed' and self.status == 'Completed' and self.tracking_number:
            subject = 'Votre commande a été livré'
            message = render_to_string(
                'orders/emails/delivery_confirmed_email.html', {'order': self})
            send_mail(subject, '', settings.DEFAULT_FROM_EMAIL,
                      [self.email], html_message=message)
            print(message)
        # Ajuster la méthode de livraison pour les commandes en France
        
       
        if self.country == 'France' and not self.pk:
            self.delivery_method = 'Colissimo'
            super().save(update_fields=['delivery_method'])


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
import slugify
from category.models import Category
from mptt.models import TreeForeignKey

from userauths.models import Account


class Product(models.Model):
    product_name = models.CharField(max_length=500)
    product_slug = models.SlugField(null=False, blank=False)
    product_price = models.PositiveIntegerField()
    itemNumber = models.PositiveIntegerField(unique =False, null=True, blank=True)
    product_stock = models.IntegerField(default=1, unique =False)
    category = TreeForeignKey(Category, on_delete=models.CASCADE)
    product_description = models.TextField(null=True, blank=True)
    product_cleaning = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
                    
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.product_slug])

    def price_with_tax(self):
        return str(self.product_price + self.product_price*20/100)

    def __str__(self):
        return self.product_slug

    @property
    def photoURL(self):
        try:
            url = self.product_home_carousel_image
        except:
            url = ''
        print('URL :', url)
        return url
    
    def number(self):
        count = Variation.objects.count()
        if count == 0:
            return 1
        else:
            last_object = Variation.objects.order_by('-id')[0]
            return last_object.id + 1
    def save(self, *args, **kwargs):
        if not self.itemNumber:
            self.itemNumber=self.number()
        if not self.product_name:
            self.product_name = self.product.product_name + '-' + self.color.name
        if not self.product_slug:
            self.product_slug= slugify(self.product_name)
                
        context = super().save(*args, **kwargs)
        return context


class Color(models.Model):
    name=models.CharField(max_length=100, unique=True)
    colorCode=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Size(models.Model):
    size=models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return str(self.size)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_number = models.PositiveBigIntegerField(unique=False, null=True, blank=True)
    color=models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    is_available = models.BooleanField(default=True)
    created_date = models.DateField(auto_now=True)


    def __str__(self):
        return self.product.product_name

class VariationImages(models.Model):
    title = models.CharField(max_length=500, blank=True, null = True)
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)
    variation_image = models.ImageField(upload_to='static/variation_images/', verbose_name=("variation_image"))
    variation_image_slug = models.SlugField(null=True, blank=True)
    def __str__(self):
        return str(self.title)  # on met str(...) pour convertir en string

    
    
class Wishlist(models.Model):
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    product =models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "wishlists"
    def __str__(self):
        return self.product.product_name
   
class Photo(models.Model):
    title = models.CharField(max_length=500, blank=True, null = True)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='photos')
    # photo_name = models.ImageField(upload_to='stactic/photos/', verbose_name=("image"))
    product_image = models.ImageField(upload_to='static/photos/', verbose_name=("image"))
    photo_slug = models.SlugField(null=True, blank=True)
    def __str__(self):
        return str(self.product_image)  # on met str(...) pour convertir en string

    @property
    def photoURL(self):
        try:
            url = self.photo_name.url
        except:
            url = ''
        print('URL :', url)
        return

orders/forms.py
from django import forms
from .models import Order

COUNTRY_CHOICES = [
    ('US', 'United States'),
    ('FR', 'France'),
    ('CIV', "Côte d'Ivoire"),
    ('BN', 'Benin'),
    ('It', 'Italie'),
    ('ALL', 'Allemagne'),
    ('CA', "Canada"),
    ('Be', 'Belgique'),
    # Add more countries as needed
]

ZIP_CHOICES = [
    ('+1', 'United States +1'),
    ('+33', 'France +33'),
    ('+225', "Côte d'Ivoire +225"),
    ('+226', 'Benin +226'),
    ('+42', 'Italie +42'),
    ('+4', 'Allemagne +4'),
    ('+1', "Canada +1"),
    ('+34', 'Belgique +34'),
    # Add more countries as needed

]
 
DELIVERY_METHOD = (
        ("DHL", "DHL"),
        ("Colissimo", "Colissimo"),
    )

PAYMENT_METHOD = (
        ("Card", "Card"),
        ("Paypal", "Paypal"),
    )
class OrderForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "inputText", "name": "first_name", "placeholder":""}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "inputText", "name": "last_name", "placeholder":""}))
    phone = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "number", "name": "phone"}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={"class": "inputText", "name": "email", "placeholder":""}))
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, widget=forms.Select(attrs={"class": "country-select", "name": "country", "id":"country"}))    
    address_line_1 = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"", "name":"address_line_1"}))
    address_line_1 = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"cmyPass", "name":"address_line_2"}))
    postcode = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"postcode", "name":"postcode"}))
    city = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"city", "name":"city"}))
    zip_code = forms.ChoiceField(choices=ZIP_CHOICES, widget=forms.Select(attrs={"class": "code-phone", "id":"zip_code", "name":"zip_code"}))
    delivery_method = forms.ChoiceField(choices=DELIVERY_METHOD, widget=forms.RadioSelect(attrs={"name": "delivery_method", "class": "delivery_method_inputs"}))
    payment_method = forms.ChoiceField(choices=PAYMENT_METHOD, widget=forms.RadioSelect(attrs={"name": "payment_method", "class": "payment_method_inputs"}))

    class Meta:
        model = Order
        fields = ['first_name', 'zip_code', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2',
                  'country', 'city', 'postcode', 'payment_method', 'delivery_method', 'postcode']
        widgets = {
            'delivery_method': forms.RadioSelect(),
            'payment_method': forms.RadioSelect(),
        }
    def __init__(self, *args, **kwargs):
        user_country = kwargs.pop('user_country', None)
        super(OrderForm, self).__init__(*args, **kwargs)
        
        # Modifier les choix disponibles pour delivery_method en fonction du pays de l'utilisateur
        if user_country == 'FR':
            self.fields['delivery_method'].choices = [('Colissimo', 'Colissimo')]
            self.fields['delivery_method'].initial = 'Colissimo'
            self.fields['payment_method'].initial = 'Card'

        else:
            # Assumez ici vos autres options de livraison par défaut
            self.fields['delivery_method'].choices = [('DHL', 'DHL')]
            self.fields['delivery_method'].initial = 'DHL'
            self.fields['payment_method'].initial = 'Card'

        

templates/user/dashboard/address.html
{% extends '../../main.html' %} {% load static %} {% block title %} {{
    user.username}} | Dashboard {% endblock %} {% block content %}
    <link rel="stylesheet" href=" {% static 'assets/css/user/dashboard.css' %}" />
    
    <main class="dashboad-main">
    
      <aside class="dashboard-left-side">
          <!-- Dashboard nav -->
        {% include './include/dashboard_nav.html' %}
           <!-- End Dashboard nav -->
      </aside>
    
      <aside class="dashboard-right-side">
        <div class="dashboard-right-contents" id="dashboard-right-contents">
          {% include './include/address_content.html' %} 
        </div>
      </aside>
    </main>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    
    {% endblock content %}
    

templates/user/dashboard/address_content.html
{% load static %}

<ul class="db_content address-content">
  <li class="db-address-infos">Address</li>
  <li class="db-address-container">
    <ul>
      <li class="db-address-owner">Prince Yekpahi</li>
      <li class="db-x">1 rue Ingres</li>
      <li class="db-x">Chez Moi</li>
      <li class="db-x">Le Blanc-Mesnil 93150</li>
      <li class="db-x">France</li>
      <li class="db-x">+33752376667</li>
      <li class="db-edit-x"><a href="">Edit</a></li>
    </ul>
  </li>
</ul>

<script>
  console.log("salut")
  const tabs = document.querySelectorAll('.tabs-link');
  console.log(tabs)
  const all_content = document.querySelectorAll('.db_content');
  tabs.forEach((tab, index) => {
    tab.addEventListener('click', (e) => {
      tabs.forEach(tab=>{tab.classList.remove("active")});
      tab.classList.add('active');
      all_content.forEach(content=>{content.classList.remove('active')});
      all_content[index].classList.add('active');
    })
  })
</script>

templates/user/dashboard/change_password.html
{% extends '../../main.html' %} {% load static %} {% block title %} {{
    user.username}} | Dashboard {% endblock %} {% block content %}
    <link rel="stylesheet" href=" {% static 'assets/css/user/dashboard.css' %}" />
    
    <main class="dashboad-main">
    
      <aside class="dashboard-left-side">
          <!-- Dashboard nav -->
        {% include './include/dashboard_nav.html' %}
           <!-- End Dashboard nav -->
      </aside>
    
      <aside class="dashboard-right-side">
        <div class="dashboard-right-contents" id="dashboard-right-contents">
          {% include './change_password_content.html' %} 
        </div>
      </aside>
    </main>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    
    {% endblock content %}
    

templates/user/dashboard/change_password_content.html
<section class="section-conten padding-y bg">
{% include './include/alerts.html' %}
<div class="container">
	<div class="row">
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change Your Password</strong>
		</header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-12">
				<form action="{% url 'change_password' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<label>Current Password</label>
						<input type="password" name="current_password"
							   placeholder="Current Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Create New Password</label>
						<input type="password" name="new_password"
							   placeholder="Create New Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Confirm New Password</label>
						<input type="password" name="confirm_password"
							   placeholder="Confirm New Password" class="form-control" required>
					</div>
					<input type="submit" value="Submit" class="btn btn-primary">
				</form>
              </div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>
</section>

templates/user/dashboard/dashboard.html
{% extends '../../main.html' %} 

{% load static %} 
{% block title %} {{user.username}} | Dashboard {% endblock %} {% block content %}
<link rel="stylesheet" href=" {% static 'assets/css/user/dashboard.css' %}" />

<main class="dashboad-main">
  <aside class="dashboard-left-side">
          <!-- Dashboard nav -->
          {% include './include/dashboard_nav.html' %}
          <!-- End Dashboard nav -->
  </aside>
  <aside class="dashboard-right-side">
    <div class="dashboard-right-contents" id="dashboard-right-contents">
      {% include './personal_infos_content.html' %} 
    </div>
  </aside>
</main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


{% endblock content %}

templates/user/dashboard/dashboardx.html
{% extends '../main.html' %} {% load static %} 
{% block content %}
<link rel="stylesheet" href=" {% static 'assets/css/user/dashboard.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

<div class="container">
    <div class="row profile">
        {% include 'partials/alert.html' %}
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<!-- <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt=""> -->
                   
                    
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<span class="hidden-xs">Jason Davis</span>
					</div>
					<div class="profile-usertitle-job">Developer
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							<span class="hidden-xs">Personal<span> </a>
						</li>
						<li>
							<a href="https://codepen.io/jasondavis/pen/xRerWB?editors=1000" >
							<i class="glyphicon glyphicon-user"></i>
							<span class="hidden-xs">Overview<span> </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-ok"></i>
							<span class="hidden-xs">Orders <span></a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-flag"></i>
							<span class="hidden-xs">My Wishlist <span></a>
						</li>
                            <li>
							<a href="#">
							<i class="glyphicon glyphicon-shopping-cart"></i>
							<span class="hidden-xs">Shopping Bag<span> </a>
                            
						</li>
                        
					</ul>
				</div>
				<!-- END MENU -->
              
     <div class="portlet light bordered">
                                                <!-- STAT -->
                                                <div class="row list-separated profile-stat">
                                                    <div class="col-md-4 col-sm-4 col-xs-6">
                                                        <div class="uppercase profile-stat-title"> 37 </div>
                                                        <div class="uppercase profile-stat-text"> Projects </div>
                                                    </div>
                                                    <div class="col-md-4 col-sm-4 col-xs-6">
                                                        <div class="uppercase profile-stat-title"> 51 </div>
                                                        <div class="uppercase profile-stat-text"> Tasks </div>
                                                    </div>
                                                    <div class="col-md-4 col-sm-4 col-xs-6">
                                                        <div class="uppercase profile-stat-title"> 61 </div>
                                                        <div class="uppercase profile-stat-text"> Uploads </div>
                                                    </div>
                                                </div>
                                                <!-- END STAT -->
                                                <div>
                                                    <h4 class="profile-desc-title">About Jason Davis</h4>
                                                    <span class="profile-desc-text"> Lorem ipsum dolor sit amet diam nonummy nibh dolore. </span>
                                                    <div class="margin-top-20 profile-desc-link">
                                                        <i class="fa fa-globe"></i>
                                                        <a href="https://www.apollowebstudio.com">apollowebstudio.com</a>
                                                    </div>
                                                    <div class="margin-top-20 profile-desc-link">
                                                        <i class="fa fa-twitter"></i>
                                                        <a href="https://www.twitter.com/jasondavisfl/">@jasondavisfl</a>
                                                    </div>
                                                    <div class="margin-top-20 profile-desc-link">
                                                        <i class="fa fa-facebook"></i>
                                                        <a href="https://www.facebook.com/">JasonDavisFL</a>
 </div></div></div>                                               
                                              
                                              
              
			</div>
		</div>
		<div class="col-md-9 order-content">
          
		<div class="form_main col-md-4 col-sm-5 col-xs-7">
                <h4 class="heading"><strong>Personal </strong> Contact <span></span></h4>
                <div class="form">
                <form action="" method="" id="contactFrm" name="contactFrm">
                    <input type="text" required="" placeholder="Name" value="" name="name" class="txt">
                    <input type="text" required="" placeholder="Email" value="" name="email" class="txt">
                    <input type="password" required="" placeholder="Change Pwd" value="" name="password" class="txt"><br>
                    <button type="button" class="btn btn-default">Update</button>
                </form>
            </div>
            </div>
            
	</div>
		
		
	</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock content %}

templates/user/dashboard/edit_profile.html
{% extends '../../main.html' %} {% load static %} 
{% block title %} {{user.username}} | Dashboard {% endblock %} 

{% block content %}
<link rel="stylesheet" href=" {% static 'assets/css/user/dashboard.css' %}" />

<main class="dashboad-main">
  <aside class="dashboard-left-side">
          <!-- Dashboard nav -->
          {% include './include/dashboard_nav.html' %}
          <!-- End Dashboard nav -->
  </aside>
  <aside class="dashboard-right-side">
    <div class="dashboard-right-contents" id="dashboard-right-contents">
      {% include './edit_profile_content.html' %} 
    </div>
  </aside>
</main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


{% endblock content %}

templates/user/dashboard/orders.html
{% extends '../../main.html' %} {% load static %} 
{% block title %} {{user.username}} | Dashboard {% endblock %} {% block content %}
    <link rel="stylesheet" href=" {% static 'assets/css/user/dashboard.css' %}" />
    
    <main class="dashboad-main">
      <aside class="dashboard-left-side">
   <!-- Dashboard nav -->
   {% include './include/dashboard_nav.html' %}
   <!-- End Dashboard nav -->
      </aside>
      <aside class="dashboard-right-side">
        <div class="dashboard-right-contents" id="dashboard-right-contents">
          {% include './orders_content.html' %} 
        </div>
      </aside>
    </main>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    
    {% endblock content %}
    

templates/user/dashboard/orders_content.html
{% load static %}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
/>

<ul class="db_content orders-content" id="tab-content">
  <li class="db-orders-infos">My orders</li>
  <li class="db-orders-container">
    <table>
      <tr class="db-orders-header">
        <th>Order ID</th>
        <th>Product name</th>
        <th>Address</th>
        <th>Date</th>
        <th>Price</th>
        <th>Status</th>
        <th>Details</th>
      </tr>

      <!-- One Product -->
      {% for order in orders %}
      <tr class="db-orders-contents">
        <td>#{{ order.order_number }}</td>

        {% for order_product in order.orderproduct_set.all %}
        <td class="db-product-name-and-image">
          <ul>
            <li class="db-product-image">
              {% for variation in order_product.variations.all %}
              {% with variation.variationimages_set.first as first_image %}
                  {% if first_image %}
                      <img src="{{ first_image.variation_image.url }}" alt="{{ first_image.title }}">
                  {% endif %}
              {% endwith %}
          {% endfor %}

            </li>
            <li class="db-product-name">{{ order_product.product.product_name }}</li>
          </ul>
        </td>
        {% endfor %}
        <td>{{ order.address_line_1 }} {{ order.address_line_2 }}, {{ order.city }} - {{ order.postcode }}, {{ order.country }}</td>
        <td>{{ order.created_at }}</td>
        <td>{{ order.order_total }} Eur</td>
        <td>
          <span class="db-status-td" style="color: rgb(7, 100, 7)"
            >{{ order.status }}</span
          >
        </td>
        <td class="db-see-product">
          <a href=""
            ><span class="material-symbols-outlined"> visibility </span></a
          >
        </td>
      </tr>
      {% endfor %}
      <!-- End One Product -->

    </table>
  </li>
</ul>

<script>
  console.log("salut")
  const tabs = document.querySelectorAll('.tabs-link');
  console.log(tabs)
  const all_content = document.querySelectorAll('.db_content');
  tabs.forEach((tab, index) => {
    tab.addEventListener('click', (e) => {
      tabs.forEach(tab=>{tab.classList.remove("active")});
      tab.classList.add('active');
      all_content.forEach(content=>{content.classList.remove('active')});
      all_content[index].classList.add('active');
    })
  })
</script>

templates/user/dashboard/personal_infos_content.html
<ul class="db_content personal-infos-contents" id="tab-content">
    <li class="db-personal-infos">My account - Personal informations</li>
    <li class="db-fullname">{{request.user.last_name}} {{request.user.first_name}}</li>
    <li class="db-email">{{request.user.email}}</li>
    <li class="db-edit">
        <ul>
            <li><a href="">Edit account</a></li>
            <li><a href="">Edit password</a></li>
        </ul>
    </li>
</ul>